# -*- coding: utf-8 -*-
"""Project 1 DARA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWm2Oep20-f9m6q0rPfxTHQ-ERTpDjXM

I will start by first cleaning the dataset, we have been told that the dataset contains column names with whitespace as well as duplicate or missing values. I will;
1. Clean whitespace from column names.
2. Drop all missing values from the dataset
3. Check and remove any duplicate files if present.

After this I will proceed to perform the analysis.
"""

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# read in file into the environment and remove whitespace
movies = pd.read_csv("movie_dataset.csv", skipinitialspace=True)

# view file and stats
print(movies.shape)
print(movies.describe())
movies.head()

"""What is the highest rated movie in the dataset?"""

# drop any missing values from the dataset
movies_1 = movies.dropna().drop_duplicates()

# What is the highest rated movie in the dataset
movies_1.loc[movies_1["Rating"].idxmax()]

"""What is the average revenue of movies from 2015 to 2017 in the dataset?
Note, since the answer will be effected by how you dealt with missing values a range has been provided.
"""

rev_2015_2017 = movies_1[(movies_1["Year"] >= 2015) & (movies_1["Year"] <= 2017)]["Revenue (Millions)"].mean()
print(rev_2015_2017)

"""What is the average revenue of all movies in the dataset?
Note, since the answer will be effected by how you dealt with missing values a range has been provided.
"""

avg_revenue = movies_1["Revenue (Millions)"].mean()
print(avg_revenue)

"""How many movies were released in the year 2016?"""

n_movies_16 = movies[movies["Year"] == 2016]["Title"].count()
print(n_movies_16)

"""How many movies were directed by Christopher Nolan?"""

chris_movie = movies[movies["Director"] == "Christopher Nolan"]["Title"].count()
print(chris_movie)

"""How many movies in the dataset have a rating of at least 8.0?"""

movie_gret8 = movies[movies['Rating'] >= 8.0]['Title'].count()
print(movie_gret8)

"""What is the median rating of movies directed by Christopher Nolan?"""

chris_movie_rating = movies[movies["Director"] == "Christopher Nolan"]["Rating"].mean()
print(chris_movie_rating)

"""Find the year with the highest average rating?"""

max_year = movies_1.groupby('Year')['Rating'].mean()
print(max_year.idxmax())

"""What is the percentage increase in number of movies made between 2006 and 2016?"""

n_movies_2006 = movies[movies["Year"] == 2006]["Title"].count()
n_movies_2016 = movies[movies["Year"] == 2016]["Title"].count()
perc_increase = (n_movies_2016 - n_movies_2006) / n_movies_2006 * 100
print(perc_increase)

"""Find the most common actor in all the movies?

Note, the "Actors" column has multiple actors names. You must find a way to search for the most common actor in all the movies.
"""

# Find the most common actor in all the movies?
# Note, the "Actors" column has multiple actors names. You must find a way to search for the most common actor in all the movies.
movies_1["Actors"].str.split(", ", expand=True).stack().value_counts().idxmax()

"""How many unique genres are there in the dataset?

Note, the "Genre" column has multiple genres per movie. You must find a way to identify them individually.
"""

# How many unique genres are there in the dataset?
# Note, the "Genre" column has multiple genres per movie. You must find a way to identify them individually.
movies_1["Genre"].str.split(",", expand=True).stack().value_counts().count()